services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: contact-app-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - contact-app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./mycontacts-backend
      dockerfile: Dockerfile
    container_name: contact-app-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - contact-app-network
    volumes:
      - ./mycontacts-backend:/app
      - /app/node_modules

  # Frontend React App
  frontend:
    build:
      context: ./mycontacts-frontend
      dockerfile: Dockerfile
    container_name: contact-app-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - contact-app-network

volumes:
  mongodb_data:
    driver: local

networks:
  contact-app-network:
    driver: bridge
